export * from './adController.service';
import { AdControllerService } from './adController.service';
export * from './carpoolingController.service';
import { CarpoolingControllerService } from './carpoolingController.service';
export * from './chatController.service';
import { ChatControllerService } from './chatController.service';
export * from './companyController.service';
import { CompanyControllerService } from './companyController.service';
export * from './complaintController.service';
import { ComplaintControllerService } from './complaintController.service';
export * from './deliveryController.service';
import { DeliveryControllerService } from './deliveryController.service';
export * from './fastPostController.service';
import { FastPostControllerService } from './fastPostController.service';
export * from './leaveController.service';
import { LeaveControllerService } from './leaveController.service';
export * from './leaveSettingsController.service';
import { LeaveSettingsControllerService } from './leaveSettingsController.service';
export * from './leaveStatisticsController.service';
import { LeaveStatisticsControllerService } from './leaveStatisticsController.service';
export * from './notificationController.service';
import { NotificationControllerService } from './notificationController.service';
export * from './orderController.service';
import { OrderControllerService } from './orderController.service';
export * from './panierController.service';
import { PanierControllerService } from './panierController.service';
export * from './paymentController.service';
import { PaymentControllerService } from './paymentController.service';
export * from './productController.service';
import { ProductControllerService } from './productController.service';
export * from './promotionController.service';
import { PromotionControllerService } from './promotionController.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './vehicleController.service';
import { VehicleControllerService } from './vehicleController.service';
export const APIS = [AdControllerService, CarpoolingControllerService, ChatControllerService, CompanyControllerService, ComplaintControllerService, DeliveryControllerService, FastPostControllerService, LeaveControllerService, LeaveSettingsControllerService, LeaveStatisticsControllerService, NotificationControllerService, OrderControllerService, PanierControllerService, PaymentControllerService, ProductControllerService, PromotionControllerService, UserControllerService, VehicleControllerService];
