/**
 * SpeedyGo API
 * Navigators Team API
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Ad { 
    id?: string;
    title?: string;
    description?: string;
    image?: string;
    category?: Ad.CategoryEnum;
    startDate?: string;
    endDate?: string;
    status?: string;
}
export namespace Ad {
    export type CategoryEnum = 'CARPOOLING' | 'FASTPOST' | 'PRODUCT' | 'OTHER';
    export const CategoryEnum = {
        Carpooling: 'CARPOOLING' as CategoryEnum,
        Fastpost: 'FASTPOST' as CategoryEnum,
        Product: 'PRODUCT' as CategoryEnum,
        Other: 'OTHER' as CategoryEnum
    };
}


