/**
 * SpeedyGo API
 * API documentation for SpeedyGo
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Carpooling { 
    id?: string;
    driverName?: string;
    pickupLocation?: string;
    dropoffLocation?: string;
    departureTime?: string;
    availableSeats?: number;
    pricePerSeat?: number;
    typeservice?: Carpooling.TypeserviceEnum;
}
export namespace Carpooling {
    export type TypeserviceEnum = 'Carpooling' | 'ExpressTrip' | 'LongDistanceTrip';
    export const TypeserviceEnum = {
        Carpooling: 'Carpooling' as TypeserviceEnum,
        ExpressTrip: 'ExpressTrip' as TypeserviceEnum,
        LongDistanceTrip: 'LongDistanceTrip' as TypeserviceEnum
    };
}


