/**
 * SpeedyGo API
 * API documentation for SpeedyGo
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FastPost { 
    idF?: string;
    receiverName?: string;
    receiverAddress?: string;
    receiverTelNbr?: number;
    packageWeight?: number;
    packageSize?: number;
}

