/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FastPost { 
    idF?: string;
    receiverName?: string;
    receiverAddress?: string;
    receiverTelNbr?: number;
    packageWeight?: string;
    fastPostStatus?: FastPost.FastPostStatusEnum;
}
export namespace FastPost {
    export type FastPostStatusEnum = 'PENDING' | 'APPROVED' | 'REJECTED';
    export const FastPostStatusEnum = {
        Pending: 'PENDING' as FastPostStatusEnum,
        Approved: 'APPROVED' as FastPostStatusEnum,
        Rejected: 'REJECTED' as FastPostStatusEnum
    };
}


