/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Order { 
    id?: string;
    trackingNumber?: string;
    estimatedDeliveryDate?: string;
    price?: number;
    priority?: Order.PriorityEnum;
    status?: Order.StatusEnum;
    date?: string;
}
export namespace Order {
    export type PriorityEnum = 'LOW' | 'MEDIUM' | 'HIGH';
    export const PriorityEnum = {
        Low: 'LOW' as PriorityEnum,
        Medium: 'MEDIUM' as PriorityEnum,
        High: 'HIGH' as PriorityEnum
    };
    export type StatusEnum = 'PENDING' | 'INTRANSIT' | 'DELIVERED';
    export const StatusEnum = {
        Pending: 'PENDING' as StatusEnum,
        Intransit: 'INTRANSIT' as StatusEnum,
        Delivered: 'DELIVERED' as StatusEnum
    };
}


