/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Payment { 
    id?: string;
    amount?: number;
    paymentType?: Payment.PaymentTypeEnum;
    paymentDate?: string;
    status?: boolean;
    orderId?: string;
}
export namespace Payment {
    export type PaymentTypeEnum = 'CASH' | 'CARD';
    export const PaymentTypeEnum = {
        Cash: 'CASH' as PaymentTypeEnum,
        Card: 'CARD' as PaymentTypeEnum
    };
}


